### DISPLAY VARIABLES ###
# Ratio and size
WIDTH, HEIGHT = 1920, 1080
TILE_DISPLAY_WIDTH, TILE_DISPLAY_HEIGHT = 320, 180  # 240, 135  # 480, 270
CHARACTER_DISPLAY_WIDTH, CHARACTER_DISPLAY_HEIGHT = 640, 360  # 960, 540
TILE_SIZE = 16
TILE_TO_CHARACTER_RATIO = 2
# Character sizes
PLAYER_SIZE_X = 32
PLAYER_SIZE_Y = 32

### GAME PACE ###
# Game pace (around 1/60)
DT = 0.016

### GAME PHYSICS ###
# Environment forces
GRAVITY = 25 * TILE_SIZE  # 1500
# Player movement speed (by default)
PLAYER_JUMP_SPEED = 8 * TILE_SIZE  # 500
PLAYER_WALK_SPEED = 1.75 * TILE_SIZE  # 1.35 m/s

### CHARACTERS ###
# Player Controls
PLAYER_JUMP = "space"
PLAYER_WALK_RIGHT = "right"
PLAYER_WALK_LEFT = "left"
STOP_PLAYER_JUMP = "no_space"
STOP_PLAYER_WALK_RIGHT = "no_right"
STOP_PLAYER_WALK_LEFT = "no_left"
# Game calculus delay
CHARACTER_STATUS_DELAY = 10
